# Generated by Django 5.2 on 2025-04-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.IntegerField()),
                ('column2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
