# Generated by Django 5.2 on 2025-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBconnection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
